modLoader="javafml"
license="MIT"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/zehmaria/createlowheated/issues"
displayURL="https://github.com/zehmaria/createlowheated"
logoFile="clh_logo.png"

[[mods]]
    modId="createlowheated"
    version="${file.jarVersion}"
    displayName="Create Low Heated"
	authors="zeh_maria"
    description="Active charcoal-fueled low-heat alternative for processing and steam engine."

[[dependencies.createlowheated]]
    modId="forge"
    mandatory=true
    versionRange="[43.2.3,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.createlowheated]]
    modId="create"
    mandatory=true
    versionRange="[0.5.1.a,0.6.0)"
    ordering="NONE"
    side="BOTH"
[[dependencies.createlowheated]]
    modId="flywheel"
    mandatory=true
    versionRange="[0.6.8,0.7.0)"
    ordering="AFTER"
    side="CLIENT"
[[dependencies.createlowheated]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
