modLoader="javafml"
license="MIT"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/zehmaria/createlowheated/issues"
displayURL="https://github.com/zehmaria/createlowheated"
logoFile="logo.png"

[[mods]]
    modId="createlowheated"
    version="${file.jarVersion}"
    displayName="Create Low Heated"
	authors="zeh_maria"
    description="Active charcoal-fueled low-heat alternative for processing and steam engine."

[[dependencies.createlowheated]]
    modId="forge"
    mandatory=true
    versionRange="[47.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.createlowheated]]
    modId="create"
    mandatory=true
    versionRange="[0.5.1.a,0.6.0)"
    ordering="NONE"
    side="BOTH"
[[dependencies.createlowheated]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
